### ISSUE TITLE
Rename store_program to add_program

### ISSUE THREAD

**Issue by kevinheavey** [LiteSVM/litesvm#23]
Thoughts? It sounds more normal to me

**Comment by Aursen** [comment]
For this one, I don't want to store_program the normal way to load program. It's better to use deploy_program to have a real chain loading mechanism

**Comment by kevinheavey** [comment]
I often want to add programs I don't have the keys for though (e.g other people's programs). `store_program` gives a way to avoid the runtime's ownership checks and just put those programs at their expected address
