### ISSUE TITLE
Incorrect argument type in `owner()` from `CreateAssociatedTokenAccount`

### ISSUE THREAD

**Issue by Mathieu-Be** [LiteSVM/litesvm#89]
In `litesvm-token`:

https://github.com/LiteSVM/litesvm/blob/c1d2ea456356362bef3dd6c254214f8d9fafde08/token/src/create_ata.rs#L34-L37

This function requires a Keypair but I think a Pubkey would be enough ?

Same for `CreateAssociatedTokenAccountIdempotent`

**Comment by Aursen** [comment]
Good catch thanks you
